  # See http://www.appveyor.com/docs/appveyor-yml for many more options

build: false
version: 0.1.{build}

#images 

image: 
  - Ubuntu
  - Visual Studio 2017

# Set build info
environment:
  environment: development
  version: 0.1.$(appveyor_build_number)

  matrix:
  - scenario: ALL


for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
      mssql_instance: localhost\SQL2017
  services:
    - mssql2017
  before_test:
    # run preparation scripts
    - ps: .\tests\appveyor.prep.ps1
  test_script:
    # Test with native PS version
    - ps: .\tests\appveyor.pester.ps1
    # Collecting results
    - ps: .\tests\appveyor.pester.ps1 -Finalize
  after_test:
    - ps: .\tests\appveyor.post.ps1

- matrix:
    only:
      - image: Ubuntu
  environment:
      mssql_instance: localhost
  services:
    - mssql
  before_test:
    # run preparation scripts
    - ps: ./tests/appveyor.prep.ps1
  test_script:
    # Test with native PS version
    - ps: ./tests/appveyor.pester.ps1
    # Collecting results
    - ps: ./tests/appveyor.pester.ps1 -Finalize
  after_test:
    - ps: ./tests/appveyor.post.ps1

  

# #Configure services
# services:
#   - mssql2017
  
# Set alternative clone folder
#clone_folder: c:\github\dbops



#on_finish:
#  - ps:
